# Site settings
email: isc.suriyaa@gmail.com
description: The official website of 'The Command Line' (CL).
baseurl: "/cl.isc" # the subpath of your site, e.g. /blog/
url: "http://isc-host.github.io" # the base hostname & protocol for your site
repository: https://github.com/iSC-Host/cl.isc
