# Site settings
email: isc.suriyaa@gmail.com
description: The official website of 'The Command Line' (CL).
url: "http://isc-host.github.io/cl.isc/" # the base hostname & protocol for your site
repository: https://github.com/iSC-Host/cl.isc
